name: e2e
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - '**.rs'
      - '**.go'
      - '**.toml'
      - '**.lock'
      - '**.mod'
      - '**.sum'
      - '.github/workflows/e2e.yml'
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: v1.61
          args: --timeout 5m
          working-directory: e2e/interchaintestv8
  build:
    strategy:
      fail-fast: false
      matrix:
        test:
          # List your tests here
          - TestWithContractTestSuite/TestPlonkVerifier
          - TestWithContractTestSuite/TestGroth16Verifier
    name: ${{ matrix.test }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install just
        uses: extractions/setup-just@v2
      - name: Build Optimized Contract
        run: just build-optimize
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          check-latest: true
          cache-dependency-path: |
             e2e/interchaintestv8/go.sum
      - name: Run Tests
        run: |
          cd e2e/interchaintestv8
          go test -v -mod=readonly . -run=${{ matrix.test }}
      - name: Upload Diagnostics on Failure
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        continue-on-error: true
        with:
          path: e2e/interchaintestv8/diagnostics
          retention-days: 5
